# Generated by Django 3.0.3 on 2020-03-17 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100, null=True)),
                ('article_text', models.CharField(max_length=1000, null=True)),
                ('article_date', models.DateTimeField(default=datetime.datetime(2020, 3, 17, 9, 11, 35, 433347))),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('article_tag', models.ManyToManyField(to='articles.Tag')),
            ],
        ),
    ]
